- name : creating ec2 & r53 using playbook
  hosts:local
  connection: local
  become: yes
  vars:
     ami_id: ami-09c813fb71547fc4f
     sg_id: sg-01a477711f7deba28
     zone_id: Z04092822ZCUHU7SWZ18H
     DOMAIN_NAME: "vigi-devops.fun"
     instances:
     - mongodb
  tasks:
    - name: create ec2 instance
      amazon.aws.ec2_ionstance:
         name: "{{ item }}"
         instance_type: t3.micro
         security_group: "{{ sg_id }}"
         image_id: "{{ ami_id }}"
         tags: "{{ item }}"
      loop: "{{ instances }}"   
      register: ec2_output
    - name: print the ec2_output
      ansible.builtin.debug:
         msg: "{{ ec2_output }}"  